import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import { ThemeProvider } from '../components/custom/ThemeProvider';

const geistSans = localFont({
  weight: '100 900',
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});

const geistMono = localFont({
  weight: '100 900',
  variable: '--font-geist-mono',
  src: './fonts/GeistMonoVF.woff',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          enableSystem
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
